#!/bin/bash
set -e

# =============================================================================
# Maestro Agent Helm Values Population Script
# =============================================================================
# This script extracts values from management cluster Terraform outputs to
# populate the maestro-agent values-override.yaml file
#
# Prerequisites:
# 1. Management cluster Terraform applied with maestro_agent module
# 2. AWS credentials configured for management cluster account
# 3. Terraform state accessible
#
# Usage:
#   ./scripts/populate-maestro-agent-values.sh
#
# Or with custom path:
#   MANAGEMENT_TF_DIR=/path/to/management \
#   ./scripts/populate-maestro-agent-values.sh
# =============================================================================

# Color codes for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Default Terraform directory
MANAGEMENT_TF_DIR="${MANAGEMENT_TF_DIR:-terraform/config/management-cluster}"
OUTPUT_FILE="charts/maestro-agent/values-override.yaml"

echo "=============================================================================="
echo "Maestro Agent Helm Values Population Script"
echo "=============================================================================="
echo ""

# Validate Terraform directory exists
if [ ! -d "$MANAGEMENT_TF_DIR" ]; then
  echo -e "${RED}ERROR: Management cluster Terraform directory not found: $MANAGEMENT_TF_DIR${NC}"
  echo "Set MANAGEMENT_TF_DIR environment variable or run from repo root"
  exit 1
fi

echo "Step 1: Getting maestro-agent configuration from management cluster..."
cd "$MANAGEMENT_TF_DIR"

# Get helm_values output from maestro_agent module
HELM_VALUES=$(terraform output -json maestro_agent_helm_values 2>/dev/null || echo "{}")

if [ "$HELM_VALUES" == "{}" ] || [ "$HELM_VALUES" == "null" ]; then
  echo -e "${RED}ERROR: Could not get maestro_agent_helm_values from Terraform${NC}"
  echo "Make sure:"
  echo "  1. Management cluster Terraform has been applied"
  echo "  2. maestro_agent module is configured in main.tf"
  echo "  3. maestro_agent module outputs are exposed"
  exit 1
fi

# Extract individual values
SECRET_NAME=$(echo "$HELM_VALUES" | jq -r '.ascp.mqttCertSecretName' 2>/dev/null || echo "")
CONSUMER_NAME=$(echo "$HELM_VALUES" | jq -r '.maestro.consumerName' 2>/dev/null || echo "")

cd - > /dev/null

# Validate outputs
if [ -z "$SECRET_NAME" ] || [ "$SECRET_NAME" == "null" ]; then
  echo -e "${RED}ERROR: Could not extract MQTT certificate secret name${NC}"
  exit 1
fi

if [ -z "$CONSUMER_NAME" ] || [ "$CONSUMER_NAME" == "null" ]; then
  echo -e "${RED}ERROR: Could not extract consumer name (cluster ID)${NC}"
  exit 1
fi

echo -e "  ${GREEN}Consumer Name (Cluster ID): ${CONSUMER_NAME}${NC}"
echo -e "  ${GREEN}MQTT Certificate Secret: ${SECRET_NAME}${NC}"

# Step 2: Read the secret to extract broker configuration
echo ""
echo "Step 2: Reading broker configuration from Secrets Manager..."

SECRET_DATA=$(aws secretsmanager get-secret-value \
  --secret-id "$SECRET_NAME" \
  --query SecretString \
  --output text 2>&1)

if [ $? -ne 0 ]; then
  echo -e "${RED}ERROR: Could not read secret from Secrets Manager${NC}"
  echo "Make sure:"
  echo "  1. Secret exists: $SECRET_NAME"
  echo "  2. You have AWS credentials configured"
  echo "  3. You have permission to read the secret"
  echo ""
  echo "Error details:"
  echo "$SECRET_DATA"
  exit 1
fi

# Extract broker endpoint and topic prefix from secret
BROKER_ENDPOINT=$(echo "$SECRET_DATA" | jq -r '.endpoint' 2>/dev/null || echo "")
TOPIC_PREFIX=$(echo "$SECRET_DATA" | jq -r '.topicPrefix // "maestro/consumers"' 2>/dev/null || echo "maestro/consumers")

if [ -z "$BROKER_ENDPOINT" ] || [ "$BROKER_ENDPOINT" == "null" ]; then
  echo -e "${RED}ERROR: Could not extract broker endpoint from secret${NC}"
  echo "Secret must contain 'endpoint' field with IoT Core MQTT endpoint"
  exit 1
fi

echo -e "  ${GREEN}Broker Endpoint: ${BROKER_ENDPOINT}${NC}"
echo -e "  ${GREEN}Topic Prefix: ${TOPIC_PREFIX}${NC}"

# Create values-override.yaml
echo ""
echo "Step 3: Creating values-override.yaml..."

cat > "$OUTPUT_FILE" <<EOF
# =============================================================================
# Maestro Agent Helm Values Override
# =============================================================================
# Generated by scripts/populate-maestro-agent-values.sh
# Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# DO NOT commit this file to Git - cluster-specific values
#
# Architecture:
# - Certificate stored in management cluster's local Secrets Manager
# - ASCP CSI Driver mounts certificate from local account
# - Pod Identity grants IAM permissions for:
#   - Reading local Secrets Manager
# =============================================================================

# Management cluster identification
maestro:
  consumerName: "${CONSUMER_NAME}"

# MQTT Broker configuration (from regional cluster IoT Core)
broker:
  endpoint: "${BROKER_ENDPOINT}"
  topicPrefix: "${TOPIC_PREFIX}"

# ASCP CSI Driver configuration
ascp:
  mqttCertSecretName: "${SECRET_NAME}"
EOF

echo -e "  ${GREEN}✓ values-override.yaml created successfully${NC}"

echo ""
echo "=============================================================================="
echo -e "${GREEN}Maestro Agent configuration complete!${NC}"
echo ""
echo "Configuration summary:"
echo "  Consumer Name:       ${CONSUMER_NAME}"
echo "  Broker Endpoint:     ${BROKER_ENDPOINT}"
echo "  Topic Prefix:        ${TOPIC_PREFIX}"
echo "  MQTT Secret:         ${SECRET_NAME}"
echo ""
echo "Next steps:"
echo "  1. Review values: cat $OUTPUT_FILE"
echo "  2. Deploy via Helm:"
echo "     helm upgrade --install maestro-agent ./charts/maestro-agent \\"
echo "       -n maestro --create-namespace \\"
echo "       -f charts/maestro-agent/values.yaml \\"
echo "       -f charts/maestro-agent/values-override.yaml"
echo ""
echo "  Or deploy via ArgoCD:"
echo "     kubectl apply -f argocd/management-cluster/maestro-agent.yaml"
echo ""
echo "=============================================================================="
