#!/bin/bash
# =============================================================================
# Populate Maestro Server Helm values.yaml from Terraform Outputs
# =============================================================================
# This script reads Terraform outputs and updates the Helm chart values.yaml
# with the correct AWS resource ARNs, endpoints, and secret names.
#
# Usage:
#   ./scripts/populate-maestro-values.sh
#
# Prerequisites:
#   - Terraform has been applied in terraform/config/regional-cluster/
#   - yq is installed (brew install yq or https://github.com/mikefarah/yq)

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
TERRAFORM_DIR="terraform/config/regional-cluster"
VALUES_FILE="charts/maestro-server/values-override.yaml"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

echo -e "${GREEN}==============================================================================${NC}"
echo -e "${GREEN}Maestro Server Helm Values Population Script${NC}"
echo -e "${GREEN}==============================================================================${NC}"
echo ""

# Change to repository root
cd "${REPO_ROOT}"

# Check if yq is installed
if ! command -v yq &> /dev/null; then
    echo -e "${RED}Error: yq is not installed${NC}"
    echo "Please install yq:"
    echo "  - macOS: brew install yq"
    echo "  - Linux: wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq && chmod +x /usr/local/bin/yq"
    echo "  - Or see: https://github.com/mikefarah/yq"
    exit 1
fi

# Check if Terraform directory exists
if [ ! -d "${TERRAFORM_DIR}" ]; then
    echo -e "${RED}Error: Terraform directory not found: ${TERRAFORM_DIR}${NC}"
    exit 1
fi

# Note: We'll create values-override.yaml (doesn't need to exist beforehand)

echo -e "${YELLOW}Step 1: Extracting Terraform outputs...${NC}"
cd "${TERRAFORM_DIR}"

# Check if Terraform state exists
if [ ! -f "terraform.tfstate" ]; then
    echo -e "${RED}Error: No Terraform state found. Have you run 'terraform apply'?${NC}"
    exit 1
fi

# Extract Terraform outputs
echo "  - Getting MQTT certificate secret name..."
MQTT_SECRET_NAME=$(terraform output -raw maestro_server_mqtt_cert_secret_name 2>/dev/null || echo "")

echo "  - Getting database credentials secret name..."
DB_SECRET_NAME=$(terraform output -raw maestro_db_credentials_secret_name 2>/dev/null || echo "")

echo "  - Getting IoT MQTT endpoint..."
IOT_ENDPOINT=$(terraform output -raw maestro_iot_mqtt_endpoint 2>/dev/null || echo "")

# Note: No longer using External Secrets Operator - using ASCP instead

echo "  - Getting cluster name..."
CLUSTER_NAME=$(terraform output -raw cluster_name 2>/dev/null || echo "unknown")

# Validate outputs
if [ -z "${MQTT_SECRET_NAME}" ] || [ -z "${DB_SECRET_NAME}" ]; then
    echo -e "${RED}Error: Failed to retrieve required Terraform outputs${NC}"
    echo "Make sure Terraform has been successfully applied with the maestro_infrastructure module."
    exit 1
fi

echo -e "${GREEN}  ✓ Terraform outputs retrieved successfully${NC}"
echo ""

# Return to repo root
cd "${REPO_ROOT}"

echo -e "${YELLOW}Step 2: Creating values-override.yaml...${NC}"

# Create values-override.yaml with cluster-specific values
cat > "${VALUES_FILE}" << EOF
# =============================================================================
# Maestro Server Helm Values Override
# =============================================================================
# This file is generated by scripts/populate-maestro-values.sh
# DO NOT commit this file to Git - it contains cluster-specific values
#
# Generated: $(date)
# Cluster: ${CLUSTER_NAME}
# =============================================================================

# External Secrets - Secret names in AWS Secrets Manager
externalSecrets:
  mqttCertSecretName: "${MQTT_SECRET_NAME}"
  dbCredentialsSecretName: "${DB_SECRET_NAME}"

# MQTT Broker - AWS IoT Core endpoint
broker:
  endpoint: "${IOT_ENDPOINT}"
EOF

echo -e "${YELLOW}Step 3: Next steps...${NC}"
echo ""
echo "  1. Review the generated override file:"
echo "     ${GREEN}cat ${VALUES_FILE}${NC}"
echo ""
echo "  2. Verify ASCP CSI driver is installed:"
echo "     ${GREEN}kubectl get pods -n kube-system | grep csi-secrets-store${NC}"
echo ""
echo "  3. Test the Helm chart with both values files:"
echo "     ${GREEN}helm template maestro-server charts/maestro-server \\${NC}"
echo "     ${GREEN}  --namespace maestro \\${NC}"
echo "     ${GREEN}  -f charts/maestro-server/values.yaml \\${NC}"
echo "     ${GREEN}  -f charts/maestro-server/values-override.yaml${NC}"
echo ""
echo "  4. Deploy via Helm (local install, no Git required):"
echo "     ${GREEN}helm upgrade --install maestro-server charts/maestro-server \\${NC}"
echo "     ${GREEN}  --namespace maestro \\${NC}"
echo "     ${GREEN}  --create-namespace \\${NC}"
echo "     ${GREEN}  -f charts/maestro-server/values.yaml \\${NC}"
echo "     ${GREEN}  -f charts/maestro-server/values-override.yaml${NC}"
echo ""
echo "  5. Or deploy via ArgoCD (requires Git push of base values.yaml only):"
echo "     ${GREEN}kubectl apply -f argocd/regional-cluster/maestro-server.yaml${NC}"
echo "     ${GREEN}Note: ArgoCD will use values.yaml from Git, override with Kustomize or similar${NC}"
echo ""
echo -e "${GREEN}==============================================================================${NC}"
echo -e "${GREEN}✓ Done! Maestro Server values.yaml has been populated.${NC}"
echo -e "${GREEN}==============================================================================${NC}"
